// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data;

#nullable disable

namespace Store.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231129152753_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Store.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Смартфони"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ноутбуки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Стаціонарні ПК"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Годинники"
                        });
                });

            modelBuilder.Entity("Store.Data.Models.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Producers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "HP"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Korea",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 4,
                            Country = "China",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Name = "DELL"
                        });
                });

            modelBuilder.Entity("Store.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProducerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProducerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 2,
                            Model = "X",
                            Name = "iPhone",
                            Price = 600f,
                            ProducerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Count = 5,
                            Model = "15",
                            Name = "iPhone",
                            Price = 1300f,
                            ProducerId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Count = 2,
                            Name = "ElitBook",
                            Price = 2100f,
                            ProducerId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Count = 7,
                            Model = "PLUS",
                            Name = "OPTIPLEX",
                            Price = 1100f,
                            ProducerId = 5
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Count = 10,
                            Model = "5 series",
                            Name = "Apple Watch",
                            Price = 600f,
                            ProducerId = 1
                        });
                });

            modelBuilder.Entity("Store.Data.Models.Product", b =>
                {
                    b.HasOne("Store.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Store.Data.Models.Producer", "Producer")
                        .WithMany("Products")
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Producer");
                });

            modelBuilder.Entity("Store.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Store.Data.Models.Producer", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
